function t270_scroll(hash,offset,speed){var $root=$('html, body');var target="";if(speed===undefined){speed=500}
try{target=$(hash)}catch(event){console.log("Exception t270: "+event.message);return!0}
if(target.length===0){target=$('a[name="'+hash.substr(1)+'"]');if(target.length===0){return!0}}
$root.animate({scrollTop:target.offset().top-offset},speed,function(){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}});return!0}
function t570_init(recid){if($(window).width()>750){t570_setMapHeight(recid);$(window).load(function(){t570_setMapHeight(recid)});$(window).resize(function(){t570_setMapHeight(recid)})}}
function t570_setMapHeight(recid){var t570__el=$('#rec'+recid),t570__map=t570__el.find('.t-map');var t570__textwrapper=t570__el.find('.t570__col_text').height();t570__map.css('height',t570__textwrapper).trigger('sizechange')}
function t691_unifyHeights(recid){if($(window).width()>=960){$('#rec'+recid+' .t691 .t-container .t691__row').each(function(){var t691__highestBox=0;var t691__currow=$(this);$('.t691__col',this).each(function(){var t691__curcol=$(this);var t691__curcolinfo=t691__curcol.find('.t691__sectioninfowrapper');var t691__curcolpers=t691__curcol.find('.t691__personwrapper');var t691__curcolinnerheight=t691__curcolinfo.outerHeight()+t691__curcolpers.outerHeight();if(t691__curcolinnerheight>t691__highestBox){t691__highestBox=t691__curcolinnerheight}});$('.t691__col',this).css('height',t691__highestBox)})}};function t694_init(recid){var el=$('#rec'+recid);t694_setHeight(recid);$(window).resize(t_throttle(function(){t694_setHeight(recid)}));el.find('.t694').bind('displayChanged',t_throttle(function(){t694_setHeight(recid)}))}
function t694_setHeight(recid){var el=$('#rec'+recid+' .t694');var t694_ratio=el.attr('data-tile-ratio');var t694_ratioHeight=el.find('.t694__col').width()*t694_ratio;if($(window).width()>=768){el.find('.t694__row').each(function(){var t694_largestHeight=0,t694_currow=$(this);$('.t694__table',this).each(function(){var t694_curCol=$(this),t694_curColHeight=t694_curCol.find(".t694__textwrapper").outerHeight();if($(this).find(".t694__cell").hasClass("t694__button-bottom")){t694_curColHeight+=t694_curCol.find(".t694__button-container").outerHeight()}
if(t694_curColHeight>t694_largestHeight){t694_largestHeight=t694_curColHeight}});if(t694_largestHeight>t694_ratioHeight){$('.t694__table',this).css('height',t694_largestHeight)}else{if($('.t694__table',this).css('height')!=''){$('.t694__table',this).css('height','')}}})}else{el.find('.t694__table').css('height','')}}
function t698_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t698_onSuccess(t698_form){var t698_inputsWrapper=t698_form.find('.t-form__inputsbox');var t698_inputsHeight=t698_inputsWrapper.height();var t698_inputsOffset=t698_inputsWrapper.offset().top;var t698_inputsBottom=t698_inputsHeight+t698_inputsOffset;var t698_targetOffset=t698_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t698_target=t698_targetOffset-200}else{var t698_target=t698_targetOffset-100}
if(t698_targetOffset>$(window).scrollTop()||($(document).height()-t698_inputsBottom)<($(window).height()-100)){t698_inputsWrapper.addClass('t698__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t698_target},400);setTimeout(function(){t698_inputsWrapper.addClass('t698__inputsbox_hidden')},400)}
var successurl=t698_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t790_init(recid){$(".yButton .yButtonText").addClass("t790__yclients-btn-text")}